title: Shiny@DE
baseURL: http://shiny.de.ufpb.br
copyright: Copyright &copy; {year} [Departamento de Estatística/UFPB](https://ufpb.br/de)
googleAnalytics: ''
disqusShortname: ''
theme: academia-hugo
enableGitInfo: no
defaultContentLanguage: pt
hasCJKLanguage: no
defaultContentLanguageInSubdir: no
removePathAccents: yes
paginate: 10
enableEmoji: yes
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles:
  - \.ipynb$
  - .ipynb_checkpoints$
  - \.Rmd$
  - \.Rmarkdown$
  - _files$
  - _cache$
outputs:
  home:
    - HTML
    - RSS
    - JSON
  section:
    - HTML
    - RSS
blackfriday:
  angledQuotes: no
  extensions: backslashLineBreak
  hrefTargetBlank: yes
  latexDashes: yes
imaging:
  anchor: smart
  quality: 90
  resampleFilter: lanczos
taxonomies:
  author: authors
  category: categories
  publication_type: publication_types
  tag: tags
